org: ddakib
app: telegram-bot-handler
service: carpooling-telegram-bot


custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action: 'dynamodb:*'
      Resource: '*'
  environment:
    TELEGRAM_TOKEN: ${env:BOT_TOKEN}
    ALCHEMY_API_URL: ${env:ALCHEMY_API_URL}
    WALLET_PRIVATE_KEY: ${env:WALLET_PRIVATE_KEY}
    ONBOARDING_CONTRACT_ADDRESS: ${env:ONBOARDING_SERVICE_ADDRESS}
    PAYMENT_CONTRACT_ADDRESS: ${env:PAYMENT_PROCESSING_SERVICE_ADDRESS}
    WALLET_ADDRESS: ${env:WALLET_ADDRESS}
    CAR_MANAGEMENT_SERVICE_ADDRESS: ${env:CAR_MANAGEMENT_SERVICE_ADDRESS}
    ROUTING_SERVICE_API_KEY: AIzaSyDQEqeNOjLEhMSpiIp1-EnUgyJFdRGA4cI

package:
  patterns:
    - '!.venv'
    - '!.gitignore'

functions:
  handle_user_message:
    handler: src.message_handler.handler
    events:
      - http:
          path: my-first-test
          method: post
          cors: true

  handle_transaction_event_emitted:
    handler: src.ts_event_handler.handler
    events:
      - http:
          path: /smart-contract/event
          method: post
          cors: true

plugins:
  - serverless-python-requirements

resources:
  Resources:
    EthereumTransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ethereum-transactions-table
        AttributeDefinitions:
          - AttributeName: pk   # tx_hash
            AttributeType: S
          - AttributeName: gsi1_pk   # chat_id
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: gsi1_pk
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST

    ChatStateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-chat-state-table
        AttributeDefinitions:
          - AttributeName: pk   # chat_id
            AttributeType: N
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST

    UserInfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-info-table
        AttributeDefinitions:
          - AttributeName: pk   # username
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    RoutesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: routes-table-v2
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: owner_username
            AttributeType: S
          - AttributeName: route_id
            AttributeType: S
          - AttributeName: chat_id
            AttributeType: N
          - AttributeName: route_name
            AttributeType: S
          - AttributeName: source_geohash_close
            AttributeType: S
          - AttributeName: destination_geohash_close
            AttributeType: S
          - AttributeName: source_geohash_mid
            AttributeType: S
          - AttributeName: destination_geohash_mid
            AttributeType: S
          - AttributeName: source_geohash_long
            AttributeType: S
          - AttributeName: destination_geohash_long
            AttributeType: S
          - AttributeName: gsi3pk
            AttributeType: S
          - AttributeName: gsi3sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: chat_id
                KeyType: HASH
              - AttributeName: route_id
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: gsi2
            KeySchema:
              - AttributeName: route_name
                KeyType: HASH
              - AttributeName: owner_username
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: gsi3
            KeySchema:
              - AttributeName: gsi3pk
                KeyType: HASH
              - AttributeName: gsi3sk
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: gsi4
            KeySchema:
              - AttributeName: gsi4pk
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: close_range_routes_geohash
            KeySchema:
              - AttributeName: source_geohash_close
                KeyType: HASH
              - AttributeName: destination_geohash_close
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: mid_range_routes_geohash
            KeySchema:
              - AttributeName: source_geohash_mid
                KeyType: HASH
              - AttributeName: destination_geohash_mid
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: long_range_routes_geohash
            KeySchema:
              - AttributeName: source_geohash_long
                KeyType: HASH
              - AttributeName: destination_geohash_long
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'

        BillingMode: PAY_PER_REQUEST
